class GameStateProjection
  include _EventListener
  def initialize: (status: untyped, current_turn: untyped, current_rank: untyped, **untyped) -> void
  private
  def handle_game_started: (GameStartedEvent) -> void
end 