class GameStateReadModel
  RANK_NAME_MAP: Hash[Symbol, String]

  attr_reader game_state: GameState

  def initialize: (GameState game_state) -> void

  def current_state_for_display: -> Hash[Symbol, untyped]

  private

  def format_hand: -> String
  def format_rank_name: -> String
end 