class LogEventListener
  include _EventSubscriber
  def initialize: (?untyped logger) -> void
  private
  def logger: () -> untyped
  def format_event_message: (String, ?String) -> String
  def format_cards: (Array[String]) -> String
  def build_info_message: (untyped event) -> String
  def build_warning_message_if_needed: (untyped event) -> String?
end 