class GameState < ApplicationRecord
  attr_accessor status: String
  attr_accessor current_rank: String
  attr_accessor current_turn: Integer
  def hand_set: () -> Array[String]
  def assign_hand_number_from_set: (untyped) -> void
  def save!: () -> void
  def self.find_current_session: () -> GameState?
  def self.where: (*untyped) -> untyped
  def self.last: () -> untyped
  def self.new: (*untyped, **untyped) -> GameState
end 