class AggregateStore
  def current_version: () -> Integer
  def append: (untyped event, Integer) -> untyped
  def load_all_events_in_order: () -> Array[untyped]
  def latest_event: () -> untyped
  def game_already_started?: () -> bool
  private
  def build_event_from_store: (untyped store) -> untyped
  def Success: () -> untyped
  def Failure: (untyped) -> untyped
end 