class CommandContext
  module Types
    GAME_START: Symbol
    EXCHANGE_CARD: Symbol
  end
  def initialize: (Symbol, ?Card) -> void
  attr_reader type: Symbol
  attr_reader discarded_card: Card?
  def self.build_for_game_start: () -> CommandContext
  def self.build_for_exchange: (Card) -> CommandContext
end 