interface _CommandHandler
  def initialize: (EventBus) -> void
  def handle: (Command, CommandContext) -> CommandResult
  def append_to_aggregate_store: (_Event, Command) -> CommandResult
  def event_bus: () -> EventBus
  def aggregate_store: () -> Aggregates::Store
end

module CommandErrors
  class VersionConflict
    attr_reader expected_version: Integer
    attr_reader actual_version: Integer
    def initialize: (Integer, Integer) -> void    
  end

  class InvalidCommand
    attr_reader command: Command
    attr_reader reason: String
    def initialize: (command: Command, reason: String) -> void    
  end
end

module CommandHandlers
  class GameStart
    include _CommandHandler   
    
  end

  class ExchangeCard
    include _CommandHandler    
  end

  class EndGame
    include _CommandHandler    
    
  end
end

class Command
  def execute_for_game_start: (Aggregates::BoardAggregate) -> HandSet
  def execute_for_exchange_card: (Aggregates::BoardAggregate) -> _CardForCommand
  def execute_for_end_game: (Aggregates::BoardAggregate) -> void
end


class CommandContext
  module Types
    GAME_START: Symbol
    EXCHANGE_CARD: Symbol
    END_GAME: Symbol
  end
  def initialize: (Symbol, ?HandSet::Card) -> void
  attr_reader type: Symbol
  attr_reader discarded_card: HandSet::Card?
  def self.build_for_game_start: () -> CommandContext
  def self.build_for_exchange: (HandSet::Card) -> CommandContext
  def self.build_for_end_game: () -> CommandContext
end

module Aggregates
  class BoardAggregate
    def self.load_from_events: (Array[_Event] events) -> BoardAggregate
    def apply: (_Event event) -> void
    def draw_initial_hand: () -> HandSet
    def draw: () -> _CardForCommand
    def discard_to_trash: (_CardForCommand card) -> void
    def drawable?: () -> bool
    def apply_game_started_event: (_Event event) -> void
    def apply_card_exchanged_event: (_Event event) -> void
    def self.load_for_current_state: () -> BoardAggregate
    def build_cards_from_exchanged_event: (Array[_CardForCommand], CardExchangedEvent) -> Array[_CardForCommand]
  end

  class Deck
    def self.build: () -> Deck
    def draw_initial_hand: () -> HandSet
    def draw: () -> _CardForCommand
    def remove: (_CardForCommand card) -> void
    def has?: (_CardForCommand card) -> bool
    attr_reader cards: Array[_CardForCommand]
    def generate_initial_cards: () -> Array[_CardForCommand]
    def remaining_count: () -> Integer
  end

  class Trash
    def accept: (_CardForCommand card) -> void    
  end

  class Store
    def current_version: () -> Integer
    def append_event: (_Event) -> CommandResult    
    def load_all_events_in_order: () -> Array[_Event]
    def latest_event: () -> _Event?
    def game_in_progress?: () -> bool
    def build_validation_error: (ActiveRecord::RecordInvalid, Command) -> CommandErrors::InvalidCommand
    def valid_event_type?: (_Event | CommandErrors::InvalidCommand | CommandErrors::VersionConflict) -> bool
  end
end

interface _CardForCommand
  include _Card
  def suit: () -> String
  def rank: () -> String
  def valid?: () -> bool
  def ==: (_CardForCommand) -> bool
  def eql?: (_CardForCommand) -> bool
  def hash: () -> Integer
end

class CommandBus
  def initialize: (EventBus, Logger) -> void
  def execute: (Command, CommandContext) -> CommandResult
end

class CommandResult
  attr_reader event: untyped
  attr_reader error: untyped
  def initialize: (?event: untyped, ?error: untyped) -> void
  def success?: () -> bool
  def failure?: () -> bool
end

###################
# privateメソッド定義
####################
module Aggregates
  class Store
    private
    def build_event_from_event: (Event event_record) -> _Event
    def build_failer_if_conflict: (_Event, Integer) -> CommandErrors::VersionConflict?
    def add_event_to_store_may_raise_version_conflict!: (_Event, Integer) -> Event
    def version_conflict_error?: (ActiveRecord::RecordInvalid) -> bool
    def build_version_conflict_event: (_Event, Integer) -> CommandErrors::VersionConflict
    def create_event!: (_Event) -> _Event
    def raise_if_invalid_event_record: (Event event_record, Hash[String, untyped] maps) -> void
  end

  class BoardAggregate
    private
    attr_reader deck: Deck
    attr_reader trash: Trash
    attr_reader game_started: bool
    attr_writer game_started: bool
    def build_cards_from_event: (GameStartedEvent) -> Array[_CardForCommand]
    def apply_game_started_event_from_cards: (Array[_CardForCommand]) -> void
  end

  class Deck
    private
    
  end

  class Trash
    private
    attr_reader cards: Array[_CardForCommand]
  end
end

module CommandHandlers
  class GameStart    
    private
    attr_reader command: Command
    def append_event_to_store!: () -> CommandResult
    def build_already_started_error_result: () -> CommandResult?
  end

  class ExchangeCard    
    private
    def rebuild_hand_from_event: (Array[_CardForCommand], _Event) -> Array[_CardForCommand]
    def build_cards_from_exchanged_event: (Array[_CardForCommand], CardExchangedEvent) -> Array[_CardForCommand]
    def build_board_error_result_if_needed: () -> CommandResult?
    def build_game_state_error_result_if_needed: () -> CommandResult?
    def raise_if_invalid_context: (CommandContext) -> void
    def append_event_to_store!: () -> CommandResult
    attr_reader board: Aggregates::BoardAggregate
    attr_reader command: Command
  end

  class EndGame    
    private
    def validate_game_state: (Command) -> CommandResult?
    def process_end_game: (Command) -> CommandResult
    def append_event_to_store!: (Command) -> CommandResult
  end
end

class CommandBus  
  private
  attr_reader event_bus: EventBus
  attr_reader logger: Logger
  def build_handler_map: () -> Hash[Symbol, _CommandHandler]
  def log_error_if_needed: (CommandErrors::InvalidCommand | CommandErrors::VersionConflict | nil) -> void
end