class EventPublisher
  def initialize: (projection: Projection, event_listener: LogEventListener) -> void
  def subscribe: (Projection | LogEventListener) -> void
  def broadcast: (String, _Event) -> void
  attr_reader published_events: Array[_Event]
  private
  attr_reader projection: Projection
  attr_reader event_listener: LogEventListener
end


class EventBus
  def initialize: (EventPublisher) -> void
  def publish: (_Event) -> void
end 