module ReadModels
  class PlayerHandStateReadModel
    def initialize: () -> void
    def start_new_game!: (GameStartedEvent) -> void
    def exchange_card!: (CardExchangedEvent) -> void
    def current_state_for_display: () -> { status: String, hand: String, current_rank: String, rank_name: String, turn: Integer }
    def hand_set: () -> ReadModels::HandSet
    def refreshed_hand_set: () -> ReadModels::HandSet
    private
    attr_reader player_hand_state: PlayerHandState
    def format_hand: () -> String
  end
end 