---
name: rack
version: '2.2'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: e2749137770bcff57a062d47b0d08922071f3d37
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
