class Card
  VALID_SUITS: ::Array[String]
  VALID_RANKS: ::Array[String]

  attr_reader suit: String
  attr_reader rank: String

  def self.generate_available: (?Array[Card]) -> Array[Card]
  def initialize: (String) -> void
  def valid?: () -> bool
  def to_s: () -> String
  def ==: (untyped) -> bool
  def eql?: (untyped) -> bool
  def hash: () -> Integer
end 