# typed: true
module Events
  class HandCardsExchangedEvent
    @game_id: untyped

    @player_id: untyped

    @discarded_card_ids: untyped

    @new_card_ids: untyped

    @timestamp: untyped

    # @!sig attr_reader game_id: String
    # @!sig attr_reader player_id: String
    # @!sig attr_reader discarded_card_ids: Array[String]
    # @!sig attr_reader new_card_ids: Array[String]
    # @!sig attr_reader timestamp: Time
    attr_reader game_id: untyped

    # @!sig attr_reader game_id: String
    # @!sig attr_reader player_id: String
    # @!sig attr_reader discarded_card_ids: Array[String]
    # @!sig attr_reader new_card_ids: Array[String]
    # @!sig attr_reader timestamp: Time
    attr_reader player_id: untyped

    # @!sig attr_reader game_id: String
    # @!sig attr_reader player_id: String
    # @!sig attr_reader discarded_card_ids: Array[String]
    # @!sig attr_reader new_card_ids: Array[String]
    # @!sig attr_reader timestamp: Time
    attr_reader discarded_card_ids: untyped

    # @!sig attr_reader game_id: String
    # @!sig attr_reader player_id: String
    # @!sig attr_reader discarded_card_ids: Array[String]
    # @!sig attr_reader new_card_ids: Array[String]
    # @!sig attr_reader timestamp: Time
    attr_reader new_card_ids: untyped

    # @!sig attr_reader game_id: String
    # @!sig attr_reader player_id: String
    # @!sig attr_reader discarded_card_ids: Array[String]
    # @!sig attr_reader new_card_ids: Array[String]
    # @!sig attr_reader timestamp: Time
    attr_reader timestamp: untyped

    # @!sig initialize: (game_id: String, player_id: String, discarded_card_ids: Array[String], new_card_ids: Array[String]) -> void
    def initialize: (game_id: untyped, player_id: untyped, discarded_card_ids: untyped, new_card_ids: untyped) -> void

    # @!sig to_h: -> Hash[Symbol, untyped]
    def to_h: () -> { event_type: untyped, game_id: untyped, player_id: untyped, discarded_card_ids: untyped, new_card_ids: untyped, timestamp: untyped }
  end
end
