default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  database: <%= Rails.root.join("storage", "#{Rails.env}.sqlite3") %>

development:
  <<: *default

test:
  <<: *default
