class Simulator
  include _EventSubscriber
  include _FailureHandler
  attr_reader event_handled: bool
  attr_reader failure_handled: bool
  def initialize: () -> void
  def run: (_Command command) -> CommandResult

  private

  attr_reader command_bus: CommandBus
end
