class Simulator
  include _EventSubscriber
  include _FailureHandler
  attr_reader failure_handled: bool
  def initialize: (untyped logger) -> void
  def run: (CommandBus command_bus) -> untyped
  def determine_next_command: (_Event event) -> (_Command | nil)

  private

  attr_reader command_bus: CommandBus
end
