---
name: activesupport
version: '7.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 95d9b83e2727af43d6dea2ffb9e9d2d350425fe9
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
